### ISSUE TITLE
How to use `word-embedding` for French? 

### ISSUE THREAD

**Issue by LeMoussel** [ynqa/word-embedding#2]
Do you think it is possible to use `word-embedding` for French? The difficulty is to find a corpus in French.

What do you think ?

**Comment by ynqa** [comment]
The most ordinary way is to use Wikipedia each country, In French: https://dumps.wikimedia.org/frwiki/

And also if you use it, It's necessary to parse, cleanse... in order to satisfy input text format, below:
https://github.com/ynqa/word-embedding#file-io

Thanks :)

**Comment by LeMoussel** [comment]
Do you think the conversion (parse, cleanse... ) should  be done like the corpus text8 with a program that filters Wikipedia text dumps? (text8 corpus filter data: http://mattmahoney.net/dc/textdata#appendixa)

**Comment by ynqa** [comment]
It assures only simple whitespace split:
https://github.com/ynqa/word-embedding/blob/8cadc77ee543dd16af723ce9938f9d3b96d3aec2/utils/sent2words.go#L21-L29

So you get better word vectors, if you do the following operations:
For English,
- parsing. (e.g. <h1> hello world </h1> => hello world)
- stemming. (e.g. car, cars, car's, cars' => car)
- deleting period, comma, and unnecessary symbols: `?`, `!` and so on.

**Comment by LeMoussel** [comment]
OK, I do this

**Remove HTML Tags**
```
var remTags = regexp.MustCompile(`<[^>]*>`)
contentHTML := remTags.ReplaceAll([]byte(contentHTML), []byte(" "))
```

**Stemming**
I use [Snowball](https://github.com/kljensen/snowball) (A Go implementation of the Snowball stemmer)

** Remove unnecessary symbols
```
var remPunctuation = regexp.MustCompile(`[[:punct:]]`)
contentHTML = remPunctuation.ReplaceAll(contentHTML, []byte(" "))
```
