### ISSUE TITLE
Dependency broken

### ISSUE THREAD

**Issue by tbolsh** [ynqa/word-embedding#28]
go get -u github.com/ynqa/word-embedding
package github.com/chewxy/gorgonia/tensor: cannot find package "github.com/chewxy/gorgonia/tensor" in any of:
	.../chewxy/gorgonia/tensor (from $GOROOT)
	.../src/github.com/chewxy/gorgonia/tensor (from $GOPATH)

**Comment by chewxy** [comment]
This is my bad. Gorgonia moved to 0.8.0. I will send a PR to fix this

**Comment by tbolsh** [comment]
Thanks for the fast answer!

**Comment by chewxy** [comment]
gimme a few hrs. It's 1.30 am atm. Need to zzz

**Comment by chewxy** [comment]
Fixed. You should be able to get it working now if you `go get -u github.com/ynqa/word-embedding`. 

The pull request was created for full fix for anyone using `dep`
